branch-defaults:
  master:
    environment: ItsMySeatServer-env
    group_suffix: null
global:
  application_name: it's-my-seat-server
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
   on 64bit Amazon Linux/4.11.0
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
